# Generated by Django 5.0.3 on 2024-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arrets', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('depart', models.CharField(max_length=100)),
                ('arrivee', models.CharField(max_length=105)),
            ],
        ),
    ]
